import streamlit as st
st.set_page_config(layout="wide")
st.header("LOAN AND BORROWER DETAILS")
st.caption("Pre-filled values represent a typical mid-market loan and can be adjusted")

if "loan_data" not in st.session_state:
    st.session_state["loan_data"] = {
        "loan_amount": 1_000_000.0,
        "interest_rate": 8.0,
        "tenure": 5,
        "revenue": 2_000_000.0,
        "ebitda": 600_000.0,
        "cash_flow": 500_000.0
    }

loan_data = st.session_state["loan_data"]

st.subheader("LOAN DETAILS")

c1, c2, c3 = st.columns(3)

with c1:
    loan_amount = st.number_input(
        "Loan Amount",
        value=loan_data["loan_amount"],
        step=10000.0
    )
    st.caption("Total outstanding loan exposure")

with c2:
    interest_rate = st.slider(
        "Interest Rate (%)",
        1.0,
        20.0,
        value=loan_data["interest_rate"]
    )
    st.caption("Annual interest charged on the loan")

with c3:
    tenure = st.number_input(
        "Tenure (Years)",
        value=loan_data["tenure"],
        step=1
    )
    st.caption("Loan repayment period")

st.subheader("BORROWER FINANCIALS")

b1, b2, b3 = st.columns(3)

with b1:
    revenue = st.number_input(
        "Revenue",
        value=loan_data["revenue"],
        step=50000.0
    )
    st.caption("Total annual income generated by the borrower")

with b2:
    ebitda = st.number_input(
        "EBITDA",
        value=loan_data["ebitda"],
        step=10000.0
    )
    st.caption("Core operating profit before financing costs")

with b3:
    cash_flow = st.number_input(
        "Cash Flow",
        value=loan_data["cash_flow"],
        step=10000.0
    )
    st.caption("Actual cash available to service debt")

st.markdown("")

if st.button("Save Loan Data", use_container_width=True):
    st.session_state["loan_data"] = {
        "loan_amount": loan_amount,
        "interest_rate": interest_rate,
        "tenure": tenure,
        "revenue": revenue,
        "ebitda": ebitda,
        "cash_flow": cash_flow
    }
    st.success("Loan data saved successfully")
